@startuml
start

:Приветственное окно;



if (карта вставлена) then (да)

else (нет)

    :вставьте карту;
    kill

endif

:ввод пин-кода;

while (неверен) is (да) 
     if (меньше 3) then (да)
      else (3) 
          : карта заблокирована;
          stop
      endif 
        endwhile (нет)
repeat
switch (меню операций)
case (снятие наличных с банковской карты)
    :окно снятия наличных;
    :ввод пин-кода;
    while (неверен) is (да) 
         if (меньше 3) then (да)
         else (3) 
              : карта заблокирована;
              stop
         endif 
    endwhile (нет)
    :окно с выводом баланса карты и с полем для ввода желаемоц суммы;
    switch (выбор номинала)
        case (\nлюбыми)
        case (выбрать номинал)
            if (купюры есть) then (да)
            else (нет)
                :сообщение, что купюр нет;
                :предложение о выборе любых;
            endif 
    endswitch
    :ввод пин-кода;
    while (неверен) is (да) 
         if (меньше 3) then (да)
         else (3) 
              : карта заблокирована;
              stop
         endif 
    endwhile (нет)
    if (печатать чек?) then (да)
       :печать чека;
    else (нет)
    endif
    :окно с сообщением об успешной операции;
case (пополнение банковской карты путем ввода наличных)    
    :окно пополнения банковской карты наличкой;   
    :ввод пин-кода;
    while (неверен) is (да) 
         if (меньше 3) then (да)
         else (3) 
              : карта заблокирована;
              stop
         endif 
    endwhile (нет)
    :окно с выводом баланса карты и и с полем для ввода желаемой суммы для пополнения баланса;
    if (купюры прошли) then (да)
    else (нет)
        :сообщение о замене купюр;
    endif 
    :окно с выводом обновленного баланса;  
    :окно с сообщением об успешной операции;  
case (запрос баланса банковской карты )    
    :окно с выводом баланса; 
case (выписка по последним операциям с участием данной банковской карты ) 
    :окно ввода номера телефона;
    :окно выбора периода для выписки;
    :окно с сообщением об успешной операции;
case (перевод средств с карты на карту) 
    :ввод пин-кода;
    while (неверен) is (да) 
         if (меньше 3) then (да)
         else (3) 
              : карта заблокирована;
              stop
         endif 
    endwhile (нет)
    :окно с выводом баланса; 
    :окно для ввода номра карты для перевода средств;
    :окно для ввода суммы;
    while (ввод суммы) is (недостаточно)
        :сообщение, что средств недостаточно;
    endwhile (достаточно)
    :ввод пин-кода;
    while (неверен) is (да) 
         if (меньше 3) then (да)
         else (3) 
              : карта заблокирована;
              stop
         endif 
    endwhile (нет)
    :окно с выводом обновленного баланса; 
    :окно с сообщением об успешной операции;
endswitch  
repeat while (продолжить работу с банкоматом?) is (да) not (нет)
:окно с сообщением достать карту;
stop
@enduml
